### ISSUE TITLE
Switch to Github Pages

### ISSUE THREAD

**Issue by ghost** [EsmailELBoBDev2/my-personal-website#1]
Since your code doesn't have PHP in it, you can replace `.php` file types to `.html` and you can use **free** [Github Pages](https://pages.github.com/)- hosting. It works much better, doesn't have any overlay ads and it's fast.

Learn more at [https://pages.github.com/](https://pages.github.com/).

**Comment by EsmailELBoBDev2** [comment]
im using .php because heroku.com & im now using php :P & thx for your suggestion :D
